//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BajaPlantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BajaPlantilla()
        {
            this.BajasPers = new HashSet<BajasPers>();
        }
    
        public short Cod_Plaza { get; set; }
        public short Ocupacion { get; set; }
        public string GSalarial { get; set; }
        public decimal Basico { get; set; }
        public Nullable<decimal> Condiciones { get; set; }
        public Nullable<decimal> Plus { get; set; }
        public string Resolucion { get; set; }
        public byte Departamento { get; set; }
        public string MNomina { get; set; }
        public Nullable<decimal> CTecnica { get; set; }
        public Nullable<decimal> EspecialistaP { get; set; }
        public Nullable<decimal> CTecnologica { get; set; }
        public Nullable<decimal> RCITMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BajasPers> BajasPers { get; set; }
        public virtual Plazas Plazas { get; set; }
    }
}
