//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BajasPers
    {
        public short Exp { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string CarneId { get; set; }
        public string Direccion { get; set; }
        public short Mpio { get; set; }
        public short Provincia { get; set; }
        public string Pais { get; set; }
        public byte Sucursal { get; set; }
        public string Telefono { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<short> Profesion { get; set; }
        public byte CategOcup { get; set; }
        public Nullable<byte> CategDoc { get; set; }
        public Nullable<byte> CategCient { get; set; }
        public Nullable<byte> CategTecno { get; set; }
        public Nullable<short> GradoCient { get; set; }
        public Nullable<byte> Especialidad { get; set; }
        public Nullable<byte> CategBTecno { get; set; }
        public string Militancia { get; set; }
        public Nullable<System.DateTime> Baja { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
        public string Foto { get; set; }
        public Nullable<short> IdPlaza { get; set; }
        public string Motivo { get; set; }
        public string Contrata { get; set; }
        public Nullable<byte> Cargo { get; set; }
        public Nullable<decimal> Antiguedad { get; set; }
        public Nullable<decimal> ContabilidadC { get; set; }
        public Nullable<decimal> Dirigente { get; set; }
        public Nullable<decimal> GCientifico { get; set; }
        public Nullable<decimal> Gelectrogeno { get; set; }
    
        public virtual BajaPlantilla BajaPlantilla { get; set; }
    }
}
