//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas_Ausentes
    {
        public int idCuentaA { get; set; }
        public int id_cuenta { get; set; }
        public int exp { get; set; }
        public string estado { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
