//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuentas()
        {
            this.Deshabilitar = new HashSet<Deshabilitar>();
            this.Servicios = new HashSet<Servicios>();
            this.Cuentas_Ausentes = new HashSet<Cuentas_Ausentes>();
        }
    
        public int id { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> validez { get; set; }
        public string rolpc { get; set; }
        public string tpers { get; set; }
        public string nombre_usuario { get; set; }
        public string carneId { get; set; }
        public Nullable<bool> marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deshabilitar> Deshabilitar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuentas_Ausentes> Cuentas_Ausentes { get; set; }
    }
}
