//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IncideEntities : DbContext
    {
        public IncideEntities()
            : base("name=IncideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
    
        [DbFunction("IncideEntities", "PlantillaporArea")]
        public virtual IQueryable<PlantillaporArea_Result> PlantillaporArea(Nullable<int> area)
        {
            var areaParameter = area.HasValue ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<PlantillaporArea_Result>("[IncideEntities].[PlantillaporArea](@Area)", areaParameter);
        }
    }
}
