//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiciosEntities : DbContext
    {
        public ServiciosEntities()
            : base("name=ServiciosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<Deshabilitar> Deshabilitar { get; set; }
        public virtual DbSet<Razones> Razones { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Cuentas_Ausentes> Cuentas_Ausentes { get; set; }
        public virtual DbSet<Solicitud> Solicitud { get; set; }
    }
}
