//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Razones = new HashSet<Razones>();
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int id { get; set; }
        public Nullable<int> exp_benef { get; set; }
        public Nullable<System.DateTime> validez { get; set; }
        public Nullable<System.DateTime> suspencion_inicio { get; set; }
        public Nullable<System.DateTime> suspencion_fin { get; set; }
        public string rolpc { get; set; }
        public string tpers { get; set; }
        public string estado { get; set; }
        public string tsolic { get; set; }
        public string razon_suspencion { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public string usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string carneId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Razones> Razones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios { get; set; }
    }
}
